Spanish 🇪🇸🇪🇸🇪🇸
DenverCoder1/github-readme-streak-stats pull request #239
Opened 2022-05-29 07:05 UTC by abrahammurciano

## Description

Fixes # 

### Type of change

- [ ] Bug fix (added a non-breaking change which fixes an issue)
- [ ] New feature (added a non-breaking change which adds functionality)
- [ ] Updated documentation (updated the readme, templates, or other repo files)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] Tested locally with a valid username
- [ ] Tested locally with an invalid username
- [ ] Ran tests with `composer test`
- [ ] Added or updated test cases to test new features

## Checklist:

- [ ] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [ ] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

## Screenshots

2022-05-29 07:16 UTC, DenverCoder1 approved these changes
Looks great! Thanks for contributing :tada:

2022-05-29 07:34 UTC, DenverCoder1 requested changes

2022-05-29 07:34 UTC, DenverCoder1 commented on src/translations.php
> +        "es" => "Número de Contribuciones",
I think we can change this to make it shorter as discussed on Discord

```suggestion
        "es" => "Todas Contribuciones",
```

2022-05-29 07:52 UTC, DenverCoder1 approved these changes

2022-05-29 07:53 UTC, merged

2022-06-09 21:06 UTC, abrahammurciano commented
It's "Presente"

2022-06-09 21:16 UTC, DenverCoder1 commented
Do you want to make a PR or should I just add it?

2022-06-09 21:19 UTC, abrahammurciano commented
Just add it, I'm busy rn and it's such a small thing

2022-06-09 21:20 UTC, DenverCoder1 commented
Sounds good, thanks