new: jscolor as a colour picker
DenverCoder1/github-readme-streak-stats pull request #58
Opened 2021-03-31 10:48 UTC by IvoLondon

## Description

Integrating jscolor.js. Two files are added in `src/demo/js` - jscolor.js and jscolor.min.js. On the page, I have loaded the min version, to save 40kb of loading and I have left the original for reference. Happy to delete it, if you think it not necessary. 

Fixes # (issue)

### Type of change

Please delete options that are not relevant.
- [ ] New feature (added a non-breaking change which adds functionality)

## How Has This Been Tested?

If you have changed a feature of the stats cards, please describe the tests you made to verify your changes.

- [ ] Tested locally with a valid username
- [ ] Tested locally with an invalid username
- [ ] Tested locally with a username and additional parameters

## Checklist:

- [ ] I have checked to make sure no other [pull requests](https://github.com/DenverCoder1/github-readme-streak-stats/pulls?q=is%3Apr+sort%3Aupdated-desc+) are open for this issue
- [ ] The code is properly formatted and is consistent with the existing code style
- [ ] I have commented my code, particularly in hard-to-understand areas

## Screenshots
![image](https://user-images.githubusercontent.com/20727684/113132891-f3135b80-9216-11eb-94d1-90e95976ab99.png)

If you have updated the design or appearance, please include a screenshot of your changes.

2021-03-31 11:29 UTC, DenverCoder1 requested changes

2021-03-31 11:29 UTC, DenverCoder1 commented on src/demo/index.php
> +    </script>
Only 1 place is creating jscolor elements, so presets can be set in script.js instead of here

```suggestion
```

2021-03-31 11:29 UTC, DenverCoder1 commented on src/demo/js/script.js
> +      input.setAttribute("data-jscolor", "{ preset: 'customPreset' }");
Set format to `hexa` and use a default color instead of white.

`value` can be an optional parameter to the `addProperty` function:

```js
   addProperty: function (property, value = "#DD2727FF") {
	 ...
```

If `value` will be added, you can remove this from the window load event listener:

```js
	preview.addProperty(key);
    paramInput = document.querySelector(`#${key}`);
    paramInput.value = val;
```

And put this instead:

```js
    preview.addProperty(key, val);
```

Suggestion to replace the preset:

```suggestion
      input.setAttribute("data-jscolor", "{ format: 'hexa' }");
      input.value = value;
```

2021-03-31 11:30 UTC, DenverCoder1 commented
Thanks for the contribution!

I've put a couple suggestions above. Also, I would say the `jscolor.js` file that's not being used should be removed.

Let me know if you have any questions.

2021-03-31 14:39 UTC, IvoLondon commented
The changes have been done. Thank you for your help!

2021-03-31 16:06 UTC, DenverCoder1 approved these changes
Awesome! Looks good :+1: 

One thing I noticed is that on wide screens, the left section gets wider when a property is added since the color input seems to be pretty wide by default instead of taking up just the minimum space. Maybe that could be fixed by setting a max-width on the advanced parameter inputs when the screen is large enough to have the boxes side-by-side.

Also, it might be nice to have the generated markdown have 6-digit hex colors instead of 8-digit when the colors end with "FF". That can be fixed in the update function while doing the reduce on params.

Both of these changes are a bit "extra" and if you'd prefer to have it merged without these changes, that's fine. Let me know what you think.

2021-03-31 23:49 UTC, IvoLondon commented
Good feedback and well spotted, I am happy to fix these before you merge it! Thanks

2021-04-01 08:29 UTC, IvoLondon commented
I have pushed the changes, could you have a look at the two commits @DenverCoder1 . Thanks!

2021-04-01 12:10 UTC, DenverCoder1 requested changes

2021-04-01 12:10 UTC, DenverCoder1 commented on src/demo/js/script.js
> +        obj[next.id] = next.value.replace(/#/g, "").replace(/(F|f){2}$/, "");
If someone's username or theme name were to end with "ff", the last 2 letters would get cut off by this.

Maybe the pattern could check the full field to check that it is 8-digit hex before removing the FF

2021-04-01 15:46 UTC, IvoLondon commented
I've added a few checks to cover the case you mentioned above. Could you please have a look and let me know what you think? I am open to other suggestions?

2021-04-01 15:56 UTC, DenverCoder1 approved these changes

2021-04-01 15:57 UTC, DenverCoder1 commented
:+1: Looks great!

Thanks so much for contributing!

2021-04-01 15:58 UTC, merged